
// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
  require('../App/Backgrounds/Stories');
  require('../App/Components/Common/AlertMsg/stories');
  require('../App/Components/Common/Block/stories');
  require('../App/Components/Common/Calendar/stories');
  require('../App/Components/Common/CapacityPicker/stories');
  require('../App/Components/Common/CapacityPickerField/stories');
  require('../App/Components/Common/DatePickerField/stories');
  require('../App/Components/Common/Divider/stories');
  require('../App/Components/Common/DotSpacer/stories');
  require('../App/Components/Common/Dropdown/stories');
  require('../App/Components/Common/DurationPickerField/stories');
  require('../App/Components/Common/InputField/stories');
  require('../App/Components/Common/Modals/CancelConfirmModal/stories');
  require('../App/Components/Common/Modals/CapacityPickerModal/stories');
  require('../App/Components/Common/Modals/ConfirmModal/stories');
  require('../App/Components/Common/Modals/DatePickerModal/stories');
  require('../App/Components/Common/Modals/DialogModal/stories');
  require('../App/Components/Common/Modals/Modal/stories');
  require('../App/Components/Common/Modals/SportPickerModal/stories');
  require('../App/Components/Common/NavDot/stories');
  require('../App/Components/Common/NavDots/stories');
  require('../App/Components/Common/RaisedButton/stories');
  require('../App/Components/Common/RoundButton/stories');
  require('../App/Components/Common/Row/stories');
  require('../App/Components/Common/SliderWithText/stories');
  require('../App/Components/Common/Spacer/stories');
  require('../App/Components/Common/SportCard/stories');
  require('../App/Components/Common/SportPickerField/stories');
  require('../App/Components/Common/SportsList/stories');
  require('../App/Components/Common/SwitchWithText/stories');
  require('../App/Components/Common/TextField/stories');
  require('../App/Components/Common/TimePickerField/stories');
  require('../App/Components/Common/UserCircle/stories');
  require('../App/Components/DarkFooter/stories');
  require('../App/Components/DarkFooterButton/stories');
  require('../App/Components/Games/Attendees/stories');
  require('../App/Components/Games/CancelGameConfirmModal/stories');
  require('../App/Components/Games/CancelGameDoneModal/stories');
  require('../App/Components/Games/CancelGameForm/stories');
  require('../App/Components/Games/CancelMsg/stories');
  require('../App/Components/Games/ClickableAttendees/stories');
  require('../App/Components/Games/GameCanceledFlag/stories');
  require('../App/Components/Games/GameDetails/stories');
  require('../App/Components/Games/GameListCard/stories');
  require('../App/Components/Games/GameProperties/stories');
  require('../App/Components/Games/GamesList/stories');
  require('../App/Components/Games/OpenSpots/stories');
  require('../App/Components/Games/Organizer/stories');
  require('../App/Components/Games/OrganizerAndDescription/stories');
  require('../App/Components/Games/ShareGameButton/stories');
  require('../App/Components/PlanGame/DescriptionField/stories');
  require('../App/Components/PlanGame/DescriptionForm/stories');
  require('../App/Components/PlanGame/FormLayout/stories');
  require('../App/Components/PlanGame/ShareForm/stories');
  require('../App/Components/PlanGame/ShareLink/stories');
  require('../App/Components/PlanGame/SportDateTimeForm/stories');
  require('../App/Components/PlanGame/SpotForm/stories');
  require('../App/Components/ScreenSlider/Stories');
  require('../App/Components/Spots/BackgroundImage/stories');
  require('../App/Components/Spots/SpotImage/stories');
  require('../App/Components/Spots/SpotLink/stories');
  require('../App/Components/Spots/SpotListCard/stories');
  require('../App/Components/Spots/SpotListCardSmall/stories');
  require('../App/Components/Spots/SpotMap/stories');
  require('../App/Components/Spots/SpotProperties/stories');
  require('../App/Components/Spots/SpotsList/stories');
  require('../App/Components/Stories');
  require('../App/Screens/Games/CancelGameScreen/stories');
  require('../App/Screens/Games/GameDetailsScreen/stories');
  require('../App/Screens/Games/GamesListScreen/stories');
  require('../App/Screens/Games/PlayersListScreen/stories');
  require('../App/Screens/Plan/PlanGameScreen/stories');
  require('../App/Screens/Plan/ShareGameScreen/stories');
  require('../App/Screens/Plan/Stories');
  require('../App/Screens/Profile/Stories');
  require('../App/Screens/Stories');
  
}

const stories = [
  '../App/Backgrounds/Stories',
  '../App/Components/Common/AlertMsg/stories',
  '../App/Components/Common/Block/stories',
  '../App/Components/Common/Calendar/stories',
  '../App/Components/Common/CapacityPicker/stories',
  '../App/Components/Common/CapacityPickerField/stories',
  '../App/Components/Common/DatePickerField/stories',
  '../App/Components/Common/Divider/stories',
  '../App/Components/Common/DotSpacer/stories',
  '../App/Components/Common/Dropdown/stories',
  '../App/Components/Common/DurationPickerField/stories',
  '../App/Components/Common/InputField/stories',
  '../App/Components/Common/Modals/CancelConfirmModal/stories',
  '../App/Components/Common/Modals/CapacityPickerModal/stories',
  '../App/Components/Common/Modals/ConfirmModal/stories',
  '../App/Components/Common/Modals/DatePickerModal/stories',
  '../App/Components/Common/Modals/DialogModal/stories',
  '../App/Components/Common/Modals/Modal/stories',
  '../App/Components/Common/Modals/SportPickerModal/stories',
  '../App/Components/Common/NavDot/stories',
  '../App/Components/Common/NavDots/stories',
  '../App/Components/Common/RaisedButton/stories',
  '../App/Components/Common/RoundButton/stories',
  '../App/Components/Common/Row/stories',
  '../App/Components/Common/SliderWithText/stories',
  '../App/Components/Common/Spacer/stories',
  '../App/Components/Common/SportCard/stories',
  '../App/Components/Common/SportPickerField/stories',
  '../App/Components/Common/SportsList/stories',
  '../App/Components/Common/SwitchWithText/stories',
  '../App/Components/Common/TextField/stories',
  '../App/Components/Common/TimePickerField/stories',
  '../App/Components/Common/UserCircle/stories',
  '../App/Components/DarkFooter/stories',
  '../App/Components/DarkFooterButton/stories',
  '../App/Components/Games/Attendees/stories',
  '../App/Components/Games/CancelGameConfirmModal/stories',
  '../App/Components/Games/CancelGameDoneModal/stories',
  '../App/Components/Games/CancelGameForm/stories',
  '../App/Components/Games/CancelMsg/stories',
  '../App/Components/Games/ClickableAttendees/stories',
  '../App/Components/Games/GameCanceledFlag/stories',
  '../App/Components/Games/GameDetails/stories',
  '../App/Components/Games/GameListCard/stories',
  '../App/Components/Games/GameProperties/stories',
  '../App/Components/Games/GamesList/stories',
  '../App/Components/Games/OpenSpots/stories',
  '../App/Components/Games/Organizer/stories',
  '../App/Components/Games/OrganizerAndDescription/stories',
  '../App/Components/Games/ShareGameButton/stories',
  '../App/Components/PlanGame/DescriptionField/stories',
  '../App/Components/PlanGame/DescriptionForm/stories',
  '../App/Components/PlanGame/FormLayout/stories',
  '../App/Components/PlanGame/ShareForm/stories',
  '../App/Components/PlanGame/ShareLink/stories',
  '../App/Components/PlanGame/SportDateTimeForm/stories',
  '../App/Components/PlanGame/SpotForm/stories',
  '../App/Components/ScreenSlider/Stories',
  '../App/Components/Spots/BackgroundImage/stories',
  '../App/Components/Spots/SpotImage/stories',
  '../App/Components/Spots/SpotLink/stories',
  '../App/Components/Spots/SpotListCard/stories',
  '../App/Components/Spots/SpotListCardSmall/stories',
  '../App/Components/Spots/SpotMap/stories',
  '../App/Components/Spots/SpotProperties/stories',
  '../App/Components/Spots/SpotsList/stories',
  '../App/Components/Stories',
  '../App/Screens/Games/CancelGameScreen/stories',
  '../App/Screens/Games/GameDetailsScreen/stories',
  '../App/Screens/Games/GamesListScreen/stories',
  '../App/Screens/Games/PlayersListScreen/stories',
  '../App/Screens/Plan/PlanGameScreen/stories',
  '../App/Screens/Plan/ShareGameScreen/stories',
  '../App/Screens/Plan/Stories',
  '../App/Screens/Profile/Stories',
  '../App/Screens/Stories',
  
];

module.exports = {
  loadStories,
  stories,
};
