
// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
  require('../App/Backgrounds/LogoHeaderBackground/stories');
  require('../App/Backgrounds/Stories');
  require('../App/Components/Auth/LoginForm/stories');
  require('../App/Components/Auth/SignupForm/stories');
  require('../App/Components/Common/AlertMsg/stories');
  require('../App/Components/Common/Avatar/stories');
  require('../App/Components/Common/Block/stories');
  require('../App/Components/Common/Calendar/stories');
  require('../App/Components/Common/CapacityPicker/stories');
  require('../App/Components/Common/CapacityPickerField/stories');
  require('../App/Components/Common/Checkbox/stories');
  require('../App/Components/Common/DatePickerField/stories');
  require('../App/Components/Common/Divider/stories');
  require('../App/Components/Common/DotSpacer/stories');
  require('../App/Components/Common/Dropdown/stories');
  require('../App/Components/Common/DurationPickerField/stories');
  require('../App/Components/Common/InputField/stories');
  require('../App/Components/Common/Link/stories');
  require('../App/Components/Common/Menu/stories');
  require('../App/Components/Common/Modals/CancelConfirmModal/stories');
  require('../App/Components/Common/Modals/CapacityPickerModal/stories');
  require('../App/Components/Common/Modals/ConfirmModal/stories');
  require('../App/Components/Common/Modals/DatePickerModal/stories');
  require('../App/Components/Common/Modals/DialogModal/stories');
  require('../App/Components/Common/Modals/Modal/stories');
  require('../App/Components/Common/Modals/SportPickerModal/stories');
  require('../App/Components/Common/NavBar/stories');
  require('../App/Components/Common/NavBarButton/stories');
  require('../App/Components/Common/NavDot/stories');
  require('../App/Components/Common/NavDots/stories');
  require('../App/Components/Common/RaisedButton/stories');
  require('../App/Components/Common/RoundButton/stories');
  require('../App/Components/Common/Row/stories');
  require('../App/Components/Common/Slider/stories');
  require('../App/Components/Common/SliderWithText/stories');
  require('../App/Components/Common/Spacer/stories');
  require('../App/Components/Common/SportCard/stories');
  require('../App/Components/Common/SportPickerField/stories');
  require('../App/Components/Common/SportsList/stories');
  require('../App/Components/Common/SwitchWithText/stories');
  require('../App/Components/Common/TextField/stories');
  require('../App/Components/Common/TimePickerField/stories');
  require('../App/Components/DarkFooter/stories');
  require('../App/Components/DarkFooterButton/stories');
  require('../App/Components/Games/AdminMenu/stories');
  require('../App/Components/Games/Attendees/stories');
  require('../App/Components/Games/CancelGameConfirmModal/stories');
  require('../App/Components/Games/CancelGameDoneModal/stories');
  require('../App/Components/Games/CancelGameForm/stories');
  require('../App/Components/Games/CancelMsg/stories');
  require('../App/Components/Games/ClickableAttendees/stories');
  require('../App/Components/Games/EditGameDoneModal/stories');
  require('../App/Components/Games/EditGameForm/stories');
  require('../App/Components/Games/GameCanceledFlag/stories');
  require('../App/Components/Games/GameDetails/stories');
  require('../App/Components/Games/GameListCard/stories');
  require('../App/Components/Games/GameProperties/stories');
  require('../App/Components/Games/GamesList/stories');
  require('../App/Components/Games/OpenSpots/stories');
  require('../App/Components/Games/Organizer/stories');
  require('../App/Components/Games/ShareGameButton/stories');
  require('../App/Components/Layouts/ClosableLayout/stories');
  require('../App/Components/PlanGame/DescriptionSlide/stories');
  require('../App/Components/PlanGame/InviteOnly/stories');
  require('../App/Components/PlanGame/ShareGameForm/stories');
  require('../App/Components/PlanGame/ShareLink/stories');
  require('../App/Components/PlanGame/SportDateTimeSlide/stories');
  require('../App/Components/PlanGame/SpotSlide/stories');
  require('../App/Components/Profile/EditProfileForm/stories');
  require('../App/Components/Profile/ProfileDetails/stories');
  require('../App/Components/Profile/ProfileTabs/stories');
  require('../App/Components/Profile/UserMenu/stories');
  require('../App/Components/Profile/UserSpots/stories');
  require('../App/Components/ScreenSlider/stories');
  require('../App/Components/Spots/BackgroundImage/stories');
  require('../App/Components/Spots/EditSpotField/stories');
  require('../App/Components/Spots/SpotImage/stories');
  require('../App/Components/Spots/SpotLink/stories');
  require('../App/Components/Spots/SpotListCard/stories');
  require('../App/Components/Spots/SpotListCardSmall/stories');
  require('../App/Components/Spots/SpotListCardSmallBody/stories');
  require('../App/Components/Spots/SpotMap/stories');
  require('../App/Components/Spots/SpotProperties/stories');
  require('../App/Components/Spots/SpotsList/stories');
  require('../App/Components/Stories');
  require('../App/Screens/Auth/LoggedOutScreen/stories');
  require('../App/Screens/Auth/LoginScreen/stories');
  require('../App/Screens/Auth/SignupScreen/stories');
  require('../App/Screens/Games/CancelGameScreen/stories');
  require('../App/Screens/Games/EditGameScreen/stories');
  require('../App/Screens/Games/GameDetailsScreen/stories');
  require('../App/Screens/Games/GamesListScreen/stories');
  require('../App/Screens/Games/PlayersListScreen/stories');
  require('../App/Screens/Info/InfoScreen/stories');
  require('../App/Screens/Plan/PlanGameScreen/stories');
  require('../App/Screens/Plan/ShareGameScreen/stories');
  require('../App/Screens/Profile/ProfileEditScreen/stories');
  require('../App/Screens/Spots/SpotsFilterScreen/stories');
  require('../App/Screens/Spots/SpotsListScreen/stories');
  require('../App/Screens/Stories');
  
}

const stories = [
  '../App/Backgrounds/LogoHeaderBackground/stories',
  '../App/Backgrounds/Stories',
  '../App/Components/Auth/LoginForm/stories',
  '../App/Components/Auth/SignupForm/stories',
  '../App/Components/Common/AlertMsg/stories',
  '../App/Components/Common/Avatar/stories',
  '../App/Components/Common/Block/stories',
  '../App/Components/Common/Calendar/stories',
  '../App/Components/Common/CapacityPicker/stories',
  '../App/Components/Common/CapacityPickerField/stories',
  '../App/Components/Common/Checkbox/stories',
  '../App/Components/Common/DatePickerField/stories',
  '../App/Components/Common/Divider/stories',
  '../App/Components/Common/DotSpacer/stories',
  '../App/Components/Common/Dropdown/stories',
  '../App/Components/Common/DurationPickerField/stories',
  '../App/Components/Common/InputField/stories',
  '../App/Components/Common/Link/stories',
  '../App/Components/Common/Menu/stories',
  '../App/Components/Common/Modals/CancelConfirmModal/stories',
  '../App/Components/Common/Modals/CapacityPickerModal/stories',
  '../App/Components/Common/Modals/ConfirmModal/stories',
  '../App/Components/Common/Modals/DatePickerModal/stories',
  '../App/Components/Common/Modals/DialogModal/stories',
  '../App/Components/Common/Modals/Modal/stories',
  '../App/Components/Common/Modals/SportPickerModal/stories',
  '../App/Components/Common/NavBar/stories',
  '../App/Components/Common/NavBarButton/stories',
  '../App/Components/Common/NavDot/stories',
  '../App/Components/Common/NavDots/stories',
  '../App/Components/Common/RaisedButton/stories',
  '../App/Components/Common/RoundButton/stories',
  '../App/Components/Common/Row/stories',
  '../App/Components/Common/Slider/stories',
  '../App/Components/Common/SliderWithText/stories',
  '../App/Components/Common/Spacer/stories',
  '../App/Components/Common/SportCard/stories',
  '../App/Components/Common/SportPickerField/stories',
  '../App/Components/Common/SportsList/stories',
  '../App/Components/Common/SwitchWithText/stories',
  '../App/Components/Common/TextField/stories',
  '../App/Components/Common/TimePickerField/stories',
  '../App/Components/DarkFooter/stories',
  '../App/Components/DarkFooterButton/stories',
  '../App/Components/Games/AdminMenu/stories',
  '../App/Components/Games/Attendees/stories',
  '../App/Components/Games/CancelGameConfirmModal/stories',
  '../App/Components/Games/CancelGameDoneModal/stories',
  '../App/Components/Games/CancelGameForm/stories',
  '../App/Components/Games/CancelMsg/stories',
  '../App/Components/Games/ClickableAttendees/stories',
  '../App/Components/Games/EditGameDoneModal/stories',
  '../App/Components/Games/EditGameForm/stories',
  '../App/Components/Games/GameCanceledFlag/stories',
  '../App/Components/Games/GameDetails/stories',
  '../App/Components/Games/GameListCard/stories',
  '../App/Components/Games/GameProperties/stories',
  '../App/Components/Games/GamesList/stories',
  '../App/Components/Games/OpenSpots/stories',
  '../App/Components/Games/Organizer/stories',
  '../App/Components/Games/ShareGameButton/stories',
  '../App/Components/Layouts/ClosableLayout/stories',
  '../App/Components/PlanGame/DescriptionSlide/stories',
  '../App/Components/PlanGame/InviteOnly/stories',
  '../App/Components/PlanGame/ShareGameForm/stories',
  '../App/Components/PlanGame/ShareLink/stories',
  '../App/Components/PlanGame/SportDateTimeSlide/stories',
  '../App/Components/PlanGame/SpotSlide/stories',
  '../App/Components/Profile/EditProfileForm/stories',
  '../App/Components/Profile/ProfileDetails/stories',
  '../App/Components/Profile/ProfileTabs/stories',
  '../App/Components/Profile/UserMenu/stories',
  '../App/Components/Profile/UserSpots/stories',
  '../App/Components/ScreenSlider/stories',
  '../App/Components/Spots/BackgroundImage/stories',
  '../App/Components/Spots/EditSpotField/stories',
  '../App/Components/Spots/SpotImage/stories',
  '../App/Components/Spots/SpotLink/stories',
  '../App/Components/Spots/SpotListCard/stories',
  '../App/Components/Spots/SpotListCardSmall/stories',
  '../App/Components/Spots/SpotListCardSmallBody/stories',
  '../App/Components/Spots/SpotMap/stories',
  '../App/Components/Spots/SpotProperties/stories',
  '../App/Components/Spots/SpotsList/stories',
  '../App/Components/Stories',
  '../App/Screens/Auth/LoggedOutScreen/stories',
  '../App/Screens/Auth/LoginScreen/stories',
  '../App/Screens/Auth/SignupScreen/stories',
  '../App/Screens/Games/CancelGameScreen/stories',
  '../App/Screens/Games/EditGameScreen/stories',
  '../App/Screens/Games/GameDetailsScreen/stories',
  '../App/Screens/Games/GamesListScreen/stories',
  '../App/Screens/Games/PlayersListScreen/stories',
  '../App/Screens/Info/InfoScreen/stories',
  '../App/Screens/Plan/PlanGameScreen/stories',
  '../App/Screens/Plan/ShareGameScreen/stories',
  '../App/Screens/Profile/ProfileEditScreen/stories',
  '../App/Screens/Spots/SpotsFilterScreen/stories',
  '../App/Screens/Spots/SpotsListScreen/stories',
  '../App/Screens/Stories',
  
];

module.exports = {
  loadStories,
  stories,
};
