# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SportySpots' do
  pod 'AppCenter/Crashes', '~> 2.2.0'
  pod 'AppCenter/Analytics', '~> 2.2.0'
  pod 'AppCenterReactNativeShared', '~> 2.2.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SportySpots
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  pod 'Firebase/DynamicLinks', '~> 5.20.1'
  pod 'GoogleAppMeasurement', '~> 5.8.0'

  platform :ios, '9.0'

end
