# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SportySpots' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SportySpots
  pod 'AppCenter/Crashes', '~> 1.10.0'
  pod 'AppCenter/Analytics', '~> 1.10.0'
  pod 'AppCenterReactNativeShared', '~> 1.9.0'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'GoogleAppMeasurement', '~> 5.3.0'

  # pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  platform :ios, '9.0'
end
